name: ESP8266

on:
  push:
    branches: main
    paths-ignore:
    - '**.md' # Do no build on *.md changes
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6
    - run: echo $SHA
      env: 
        SHA: ${{ steps.short-sha.outputs.sha }}
    - run: echo $SHA
      env: 
        SHA: ${{ env.SHA }}
    - name: cache-pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: cache-platformio
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: setup-python
      uses: actions/setup-python@v3
    - name: install-platformio
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: update-html
      working-directory: tools/esp8266/html
      run: python convert.py
    - name: Run PlatformIO
      run: pio run -d tools/esp8266 --environment esp8266-release
    - name: rename-binary-files
      id: rename-binary-files
      working-directory: tools/esp8266/scripts
      run: python getVersion.py
    - name: create-release
      run: echo ${{ steps.rename-binary-files.outputs.name }}
